export default {
  getText(gameState) {
    const texts = gameState.language === 'en' ? {
      msg1: "I’m so done with this jealousy of yours, it’s exhausting.",
      msg2: "You’re acting like I’m doing something wrong, and I’m not.",
      msg3: "The photographer’s just working with me, that’s his job.",
      msg4: "But you keep making it out like he’s trying to steal me.",
      msg5: "He texted me today, said I was incredible on the last shoot.",
      msg6: "Even offered to take me out to celebrate the photos.",
      msg7: "I haven’t said yes, but I’m honestly thinking about it.",
      msg8: "He doesn’t make me feel like I’m constantly on trial.",
      msg9: "You’re turning this into a problem, and it’s on you.",
      msg10: "I’ve got a career, and this is part of it, like it or not.",
      msg11: "He’s planning a big campaign, wants me to be the face of it.",
      msg12: "That means more shoots, more time with him, more everything.",
      msg13: "If you can’t handle that, we’re gonna have issues.",
      msg14: "I’m not asking you to control me, I’m asking you to deal.",
      msg15: "But if you can’t, maybe we need to rethink things.",
      msg16: "I don’t want to keep fighting over this every damn day.",
      msg17: "He’s been nothing but supportive, always hyping me up.",
      msg18: "Last shoot, he spent hours getting every pose just right.",
      msg19: "The way he looks at me when I nail a shot, it’s intense.",
      msg20: "Like he actually sees me, not just some jealous guy’s girlfriend.",
      msg21: "I’m not saying I’m into him, but it’s nice to feel valued.",
      msg22: "If you keep acting like this, I might take him up on that offer.",
      msg23: "You need to figure out what you want, and fast.",
      msg24: "I’m meeting him tomorrow to talk about the campaign.",
      msg25: "Let me know if you can get over this, or we’re done.",
      msg26: "I’m not waiting around for you to make up your mind."
    } : {
      msg1: "Я так устала от твоей ревности, это выматывает.",
      msg2: "Ты ведёшь себя, будто я делаю что-то не так, а я не делаю.",
      msg3: "Фотограф просто работает со мной, это его работа.",
      msg4: "Но ты всё время делаешь из этого проблему, будто он меня уводит.",
      msg5: "Он писал мне сегодня, сказал, что я была шикарна на последней съёмке.",
      msg6: "Даже предложил отметить фотки, если я свободна.",
      msg7: "Я ещё не согласилась, но, честно, думаю об этом.",
      msg8: "Он не заставляет меня чувствовать, что я на допросе.",
      msg9: "Ты сам всё усложняешь, и это твоя проблема.",
      msg10: "У меня есть карьера, и это часть её, нравится тебе или нет.",
      msg11: "Он планирует большую кампанию, хочет, чтобы я была её лицом.",
      msg12: "Это значит больше съёмок, больше времени с ним, больше всего.",
      msg13: "Если ты не можешь с этим справиться, у нас будут проблемы.",
      msg14: "Я не прошу тебя контролировать меня, я прошу принять.",
      msg15: "Но если не можешь, может, нам стоит всё пересмотреть.",
      msg16: "Я не хочу каждый день с тобой ругаться из-за этого.",
      msg17: "Он был только поддерживающим, всегда хвалит мою работу.",
      msg18: "На прошлой съёмке он часами добивался идеальных поз.",
      msg19: "Как он смотрит на меня, когда я всё делаю правильно, это сильно.",
      msg20: "Будто он видит меня, а не просто девушку какого-то ревнивца.",
      msg21: "Не говорю, что влюблена, но приятно чувствовать себя ценной.",
      msg22: "Если будешь так продолжать, я могу согласиться на его предложение.",
      msg23: "Подумай, чего ты хочешь, и быстро.",
      msg24: "Завтра встречаюсь с ним, обсудим кампанию.",
      msg25: "Дай знать, если сможешь это принять, или мы закончим.",
      msg26: "Я не буду ждать, пока ты определишься."
    };
    return [
      { type: "received", text: texts.msg1, delay: 1000 },
      { type: "received", text: texts.msg2, delay: 2000 },
      { type: "received", text: texts.msg3, delay: 3000 },
      { type: "received", text: texts.msg4, delay: 4000 },
      { type: "received", text: texts.msg5, delay: 5000 },
      { type: "received", text: texts.msg6, delay: 6000 },
      { type: "received", text: texts.msg7, delay: 7000 },
      { type: "received", text: texts.msg8, delay: 8000 },
      { type: "received", text: texts.msg9, delay: 9000 },
      { type: "received", text: texts.msg10, delay: 10000 },
      { type: "received", text: texts.msg11, delay: 11000 },
      { type: "received", text: texts.msg12, delay: 12000 },
      { type: "received", text: texts.msg13, delay: 13000 },
      { type: "received", text: texts.msg14, delay: 14000 },
      { type: "received", text: texts.msg15, delay: 15000 },
      { type: "received", text: texts.msg16, delay: 16000 },
      { type: "received", text: texts.msg17, delay: 17000 },
      { type: "received", text: texts.msg18, delay: 18000 },
      { type: "received", text: texts.msg19, delay: 19000 },
      { type: "received", text: texts.msg20, delay: 20000 },
      { type: "received", text: texts.msg21, delay: 21000 },
      { type: "received", text: texts.msg22, delay: 22000 },
      { type: "received", text: texts.msg23, delay: 23000 },
      { type: "received", text: texts.msg24, delay: 24000 },
      { type: "received", text: texts.msg25, delay: 25000 },
      { type: "received", text: texts.msg26, delay: 26000, nextChapter: "chapter6_resist" }
    ];
  },
  getChoices(gameState) {
    return [];
  }
};