export default {
  getText(gameState) {
    const texts = gameState.language === 'en' ? {
      msg1: "Hey, I’ve been thinking about you today.",
      msg2: "You’ve been so good lately, letting me do my thing.",
      msg3: "Most guys would’ve flipped out by now, you know.",
      msg4: "But you’re just chilling, and I’m kinda into that.",
      msg5: "The photographer texted me again this morning.",
      msg6: "He’s obsessed, says I’m his best model ever.",
      msg7: "I told him I’ve got someone who’s okay with all this.",
      msg8: "He laughed, said you must be one in a million.",
      msg9: "Anyway, he’s got this new shoot planned for next week.",
      msg10: "It’s gonna be private, just him and me at his studio.",
      msg11: "But I was thinking you should come along.",
      msg12: "You could be my assistant, carry my stuff, make sure I’m set.",
      msg13: "I’d like having you there, watching me work.",
      msg14: "He wants to try some bolder shots this time.",
      msg15: "Said it’ll be artsy, maybe a bit more revealing.",
      msg16: "I haven’t decided yet, but it sounds kinda thrilling.",
      msg17: "You’d be cool with that, right? You’ve been so relaxed.",
      msg18: "I was thinking about what to wear for it.",
      msg19: "He sent me some sketches, poses he wants to try.",
      msg20: "One’s got me leaning against a wall, looking back at him.",
      msg21: "He said it’ll show off my curves perfectly.",
      msg22: "I’m leaning toward saying yes, it could be fun.",
      msg23: "You’ll be there, right? I want you to see it all.",
      msg24: "It’s gonna be intense, but I know you can handle it.",
      msg25: "Don’t let me down, okay? I’m counting on you.",
      msg26: "I’ll send you the details tomorrow. Get some sleep."
    } : {
      msg1: "Привет, я сегодня думала о тебе.",
      msg2: "Ты в последнее время такой послушный, даёшь мне свободу.",
      msg3: "Большинство парней бы уже с катушек слетели, знаешь.",
      msg4: "А ты просто спокоен, и мне это реально нравится.",
      msg5: "Фотограф опять писал мне утром.",
      msg6: "Он помешан, говорит, что я его лучшая модель за всё время.",
      msg7: "Я рассказала ему про тебя, что ты со всем миришься.",
      msg8: "Он засмеялся, сказал, что ты один на миллион.",
      msg9: "Короче, он планирует новую съёмку на следующей неделе.",
      msg10: "Будет приватно, только он и я в его студии.",
      msg11: "Но я подумала, что ты должен прийти.",
      msg12: "Можешь быть моим ассистентом, носить вещи, помогать мне.",
      msg13: "Мне бы понравилось, если бы ты смотрел, как я работаю.",
      msg14: "Он хочет попробовать более смелые кадры на этот раз.",
      msg15: "Сказал, что будет артистично, может, чуть откровеннее.",
      msg16: "Я ещё не решила, но звучит как-то волнующе.",
      msg17: "Ты же не против, да? Ты был таким спокойным.",
      msg18: "Думаю, что надеть на эту съёмку.",
      msg19: "Он прислал мне наброски, позы, которые хочет попробовать.",
      msg20: "В одной я прислоняюсь к стене, оглядываюсь на него.",
      msg21: "Сказал, что это идеально покажет мои формы.",
      msg22: "Склоняюсь к тому, чтобы согласиться, может быть весело.",
      msg23: "Ты будешь там, правда? Хочу, чтобы ты всё видел.",
      msg24: "Будет напряжённо, но я знаю, ты справишься.",
      msg25: "Не подведи меня, ладно? Я на тебя рассчитываю.",
      msg26: "Завтра пришлю детали. Спи пока."
    };
    return [
      { type: "received", text: texts.msg1, delay: 1000 },
      { type: "received", text: texts.msg2, delay: 2000 },
      { type: "received", text: texts.msg3, delay: 3000 },
      { type: "received", text: texts.msg4, delay: 4000 },
      { type: "received", text: texts.msg5, delay: 5000 },
      { type: "received", text: texts.msg6, delay: 6000 },
      { type: "received", text: texts.msg7, delay: 7000 },
      { type: "received", text: texts.msg8, delay: 8000 },
      { type: "received", text: texts.msg9, delay: 9000 },
      { type: "received", text: texts.msg10, delay: 10000 },
      { type: "received", text: texts.msg11, delay: 11000 },
      { type: "received", text: texts.msg12, delay: 12000 },
      { type: "received", text: texts.msg13, delay: 13000 },
      { type: "received", text: texts.msg14, delay: 14000 },
      { type: "received", text: texts.msg15, delay: 15000 },
      { type: "received", text: texts.msg16, delay: 16000 },
      { type: "received", text: texts.msg17, delay: 17000 },
      { type: "received", text: texts.msg18, delay: 18000 },
      { type: "received", text: texts.msg19, delay: 19000 },
      { type: "received", text: texts.msg20, delay: 20000 },
      { type: "received", text: texts.msg21, delay: 21000 },
      { type: "received", text: texts.msg22, delay: 22000 },
      { type: "received", text: texts.msg23, delay: 23000 },
      { type: "received", text: texts.msg24, delay: 24000 },
      { type: "received", text: texts.msg25, delay: 25000 },
      { type: "received", text: texts.msg26, delay: 26000, nextChapter: "chapter6_submissive" }
    ];
  },
  getChoices(gameState) {
    return [];
  }
};