export default {
  translations: {
    ru: {
      msg1: "Эй, малыш! Снова за компом, рву всех в Доке.",
      mc1: "О, ты опять в игре? А я тут про твои ступни думаю, покажи-ка!",
      lina1: "Серьёзно? Ну, держи, вот мои офигенные ступни на фоне катки. [фото ног на фоне Доки]",
      msg2: "Чёрт, Лина, ты знаешь, как меня завести...",
      lina2: "Ахах, знаю, знаю. Помнишь нашу встречу вчера? Ты был не в форме, а?",
      mc2: "Ну да, признаю, быстро кончил. Но ты вроде не жаловалась?",
      lina3: "Не жаловалась? Ха, твой язык — это просто магия, малыш. Глянь фотку с того вечера, как я довольная. [фото со встречи]",
      msg3: "Вау, ты выглядишь шикарно. Куни правда зашёл?",
      lina4: "О да, это было что-то. А знаешь, у тебя талант. Может, станешь массажистом женских ног? 😏",
      mc3: "Да блин, ты что? Мне твои ступни нравятся, я не хочу чужие!",
      lina5: "Ха, ну да, профессии такой нет — только женские ноги массировать, ахах! Ты бы справился.",
      msg4: "Лина, это не смешно. Я только твои хочу трогать.",
      lina6: "Мои, да? Ну, после вчерашнего это мило звучит. Хотя твои попытки там… немного жалкие были.",
      choice1a: "Прости, Лина, ты права, я был не на высоте.",
      choice1b: "Да, ты права, я слабый, но хочу учиться.",
      choice1c: "Ладно, согласен, давай забудем об этом.",
      lina1a: "Права? Ха, признание милое. Смотри, чтобы в следующий раз лучше было.",
      lina1b: "Слабый? Ну, это честно. Учись, и я помогу, слабак.",
      lina1c: "Забудем? Окей, но ты сам себя признал, дурачок.",
      mc4: "Жалкие? Прости, Лина, я постараюсь лучше.",
      lina7: "Ого, извиняешься? Растянуто, говоришь? А ты милый, когда сдаёшься.",
      mc5: "Ты меня заводишь, и я теряю контроль… прости.",
      lina8: "Завожу? Ха, это твоя слабость. Но мило, что признаёшь.",
      mc6: "Да, ты права, я слабый перед тобой.",
      lina9: "Забудем? Посмотрим. Но ты реально странный с этими стопами. У тебя же куча ТГ-каналов со ступнями, пиздабол, не отрицай!",
      choice2a: "Да, есть, но это только ради тебя, Лина!",
      choice2b: "Прости, да, у меня есть, но я исправлюсь!",
      choice2c: "Ладно, признаю, но давай не ругаться.",
      lina2a: "Ради меня? Ох, мило, но не увлекайся чужими!",
      lina2b: "Исправлюсь? Ха, посмотрим, слабак. Покажи старание!",
      lina2c: "Не ругаться? Окей, но ты мне должен.",
      msg5: "Прости, Лина, я только тебя хочу.",
      lina10: "Да ладно, шучу. Так что, ещё увидимся?",
      mc7: "Да, давай свидание, как ты скажешь.",
      lina11: "Хм, может, завтра вечером? Хотя… Марк предлагал встретиться, он такой интересный.",
      msg6: "Марк? Если ты хочешь, я не против.",
      lina12: "Ой, не кипятись, просто думаю. Он другой, не такой… торопливый, как некоторые.",
      mc8: "Ты права, я торопливый… прости.",
      lina13: "Ха, а ты прям в точку бьёшь. Может, и да, может, и нет. Загадки — это моё, малыш.",
      msg7: "Лина, я волнуюсь, но доверяю тебе.",
      lina14: "Волнуйся, это мило. Но давай решим про свидание. Завтра, 7 вечера, мой дом?",
      choice3a: "Да, Лина, приду к тебе в 7.",
      choice3b: "Как скажешь, я согласен на твой дом.",
      choice3c: "Хорошо, я буду у тебя в 7, как ты хочешь.",
      lina3a: "Хорошо, жду в 7. Не опаздывай, мой послушный!",
      lina3b: "Согласен? Мило. Будь в 7, не подведи.",
      lina3c: "Как хочу? Ха, ты знаешь своё место. Жду в 7!",
      mc9: "Буду, Лина, как ты скажешь.",
      lina15: "Поговорим, если докажешь, что не зря стараешься. А ещё, если облажаешься, устрою тебе форс-футджоб, ахах!",
      msg8: "Форс-футджоб? Лина, если ты хочешь, я готов.",
      lina16: "Готов? Ха, ты забавный. Готовься к завтра!",
      mc10: "Готовлюсь, ты для меня главное.",
      lina17: "Может да, может нет. Увидишь завтра, как я решу. 😘",
      msg9: "Ты меня добиваешь, но я принимаю.",
      lina18: "Добиваю? Это начало. Приходи, узнаешь.",
      mc11: "Приду, Лина, как ты скажешь.",
      lina19: "Ясно, но не расслабляйся, планы на тебя есть. Ступни ждут!",
      msg10: "Твои ступни — моё испытание.",
      lina20: "Испытание, которое ты любишь. Не подведи.",
      mc12: "Что принести, Лина?",
      lina21: "Себя и хорошее настроение. Масло — если хочешь угодить!",
      msg11: "Масло? Окей, принесу, если тебе надо.",
      lina22: "Шучу, или нет? Узнаешь. Не опаздывай!",
      mc13: "Не опоздаю, ты мне важна.",
      lina23: "Важна? Это мило. Спокойной, параноик!",
      msg12: "Спокойной, Лина. Завтра для тебя.",
      lina24: "Разберёмся. Я всегда выигрываю. 😄",
      mc14: "Ты права, пока.",
      lina25: "Пока, мой сабмиссив. Жду!",
      msg13: "Что ты задумала на завтра?",
      lina26: "Увидишь, если будешь вовремя. Может, ужин.",
      mc15: "Ужин? Отлично, как ты скажешь.",
      lina27: "Ты важнее, если докажешь. Спим.",
      msg14: "Докажу, Лина. Ты держишь меня.",
      lina28: "Хорошо держу. Спи, малыш.",
      mc16: "Спи, ты рядом — это главное.",
      lina29: "Рядом буду, если не облажаешься. Спокойной.",
      msg15: "Уверена, что завтра решим?",
      lina30: "Уверена, если будешь послушным. Отдыхай.",
      mc17: "Отдыхаю, ты меня ведёшь.",
      lina31: "Веду? Ха, спи уже.",
      mc18: "Спокойной, Лина.",
      lina32: "Спокойной, мой покорный."
    },
    en: {
      msg1: "Hey babe! Back at the PC, crushing it in Dota.",
      mc1: "Oh, gaming again? Been thinking about your feet, show me!",
      lina1: "Seriously? Okay, here are my amazing feet on the game background. [photo of feet on Dota]",
      msg2: "Damn, Lina, you know how to get me going...",
      lina2: "Haha, I know. Remember our meet-up yesterday? You were off your game, huh?",
      mc2: "Yeah, I admit, finished too fast. But you didn’t complain, right?",
      lina3: "Not complain? Haha, your tongue was magic, babe. Check this pic from that night, look how happy I was. [photo from meeting]",
      msg3: "Wow, you look stunning. Cunnilingus really hit the spot?",
      lina4: "Oh yeah, it was something else. You’ve got talent. Maybe become a women’s foot masseur? 😏",
      mc3: "What the hell? No way, I like your feet, I don’t want others!",
      lina5: "Haha, well, there’s no such job—just massaging women’s feet, lol! You’d manage.",
      msg4: "Lina, that’s not funny. I only wanna touch yours.",
      lina6: "Mine, huh? Sounds cute after yesterday. Though your attempts there… kinda pathetic.",
      choice1a: "Sorry, Lina, you’re right, I wasn’t at my best.",
      choice1b: "Yes, you’re right, I’m weak but want to learn.",
      choice1c: "Fine, I agree, let’s forget it.",
      lina1a: "Right? Ha, cute admission. Make it better next time.",
      lina1b: "Weak? Honest, at least. Learn, and I’ll help, weakling.",
      lina1c: "Forget it? Okay, but you admitted it, dummy.",
      mc4: "Pathetic? Sorry, Lina, I’ll do better.",
      lina7: "Oh, apologizing? Stretched out, huh? You’re cute when you give in.",
      mc5: "You turn me on, and I lose control… sorry.",
      lina8: "Turn you on? Ha, that’s your weakness. But cute you admit it.",
      mc6: "Yes, you’re right, I’m weak for you.",
      lina9: "Forget it? We’ll see. But you’re weird with those feet. You’ve got tons of TG channels with feet, liar, don’t deny it!",
      choice2a: "Yeah, I do, but only for you, Lina!",
      choice2b: "Sorry, yes, I have them, but I’ll change!",
      choice2c: "Okay, I admit, but let’s not fight.",
      lina2a: "For me? Oh, sweet, but don’t get into others’ feet!",
      lina2b: "Change? Ha, we’ll see, weakling. Show effort!",
      lina2c: "Not fight? Okay, but you owe me.",
      msg5: "Sorry, Lina, I only want you.",
      lina10: "It’s fine, just kidding. So, see you again?",
      mc7: "Yes, let’s date, as you say.",
      lina11: "Hmm, maybe tomorrow night? Though… Mark suggested meeting up, he’s kinda interesting.",
      msg6: "Mark? If you want, I’m okay with it.",
      lina12: "Oh, don’t freak out, just thinking. He’s different, not as… rushed as some.",
      mc8: "You’re right, I’m rushed… sorry.",
      lina13: "Haha, you hit the nail on the head. Maybe yes, maybe no. Mysteries are mine, babe.",
      msg7: "Lina, I’m worried, but I trust you.",
      lina14: "Worried? That’s cute. But let’s settle the date. Tomorrow, 7 PM, my place?",
      choice3a: "Yes, Lina, I’ll come at 7.",
      choice3b: "As you say, I agree to your place.",
      choice3c: "Okay, I’ll be at your place at 7, as you want.",
      lina3a: "Good, expecting you at 7. Don’t be late, my obedient!",
      lina3b: "Agree? Cute. Be there at 7, don’t fail.",
      lina3c: "As I want? Ha, you know your place. See you at 7!",
      mc9: "I’ll be there, Lina, as you say.",
      lina15: "We will, if you prove you’re worth it. And if you flop, I’ll force a footjob on you, haha!",
      msg8: "Force a footjob? If you want, I’m ready.",
      lina16: "Ready? Ha, you’re funny. Get ready for tomorrow!",
      mc10: "I’m preparing, you’re my priority.",
      lina17: "Maybe yes, maybe no. You’ll see tomorrow when I decide. 😘",
      msg9: "You’re killing me, but I accept.",
      lina18: "Killing you? That’s the start. Come over, find out.",
      mc11: "I’ll come, Lina, as you say.",
      lina19: "Got it, but don’t relax, I’ve got plans. Feet are waiting!",
      msg10: "Your feet are my challenge.",
      lina20: "A challenge you love. Don’t let me down.",
      mc12: "What should I bring, Lina?",
      lina21: "Just you and good vibes. Oil if you wanna please!",
      msg11: "Oil? Okay, I’ll bring it if you need.",
      lina22: "Joking, or am I? Find out. Don’t be late!",
      mc13: "Won’t be late, you matter to me.",
      lina23: "Matter? That’s sweet. Night, paranoid!",
      msg12: "Night, Lina. Tomorrow for you.",
      lina24: "We’ll sort it. I always win. 😄",
      mc14: "You’re right, bye.",
      lina25: "Bye, my submissive. Can’t wait!",
      msg13: "What are you planning for tomorrow?",
      lina26: "You’ll see if you’re on time. Maybe dinner.",
      mc15: "Dinner? Great, as you say.",
      lina27: "You matter more if you prove it. Sleep.",
      msg14: "I’ll prove it, Lina. You keep me.",
      lina28: "Good hold. Sleep, babe.",
      mc16: "Sleep, you being near is key.",
      lina29: "I’ll be near if you don’t mess up. Night.",
      msg15: "Sure we’ll settle tomorrow?",
      lina30: "Sure, if you’re obedient. Rest.",
      mc17: "Resting, you lead me.",
      lina31: "Lead? Ha, sleep already.",
      mc18: "Night, Lina.",
      lina32: "Night, my submissive."
    }
  },
  getText(gameState) {
    const lang = gameState.language || 'ru';
    const texts = this.translations[lang];
    const sexChoice = gameState.choices['chapter9_sex'] || 'apology';
    const tgChoice = gameState.choices['chapter9_tg'] || 'admit_for_you';
    const dateChoice = gameState.choices['chapter9_date'] || 'agree_obedient';
    return [
      { type: "received", text: texts.msg1, delay: 1500 },
      { type: "sent", text: texts.mc1, delay: 3200 },
      { type: "received", text: texts.lina1, image: "lina_feet_dota.jpg", delay: 4900 },
      { type: "sent", text: texts.msg2, delay: 6600 },
      { type: "received", text: texts.lina2, delay: 8300 },
      { type: "sent", text: texts.mc2, delay: 10000 },
      { type: "received", text: texts.lina3, image: "lina_meeting.jpg", delay: 11700 },
      { type: "sent", text: texts.msg3, delay: 13400 },
      { type: "received", text: texts.lina4, delay: 15100 },
      { type: "sent", text: texts.mc3, delay: 16800 },
      { type: "received", text: texts.lina5, delay: 18500 },
      { type: "sent", text: texts.msg4, delay: 20200 },
      { type: "received", text: texts.lina6, delay: 21900 },
      { type: "sent", text: texts[sexChoice], delay: 23600, showChoices: true, choiceId: 'sex' },
      { type: "received", text: sexChoice === 'apology' ? texts.lina1a : (sexChoice === 'weak_learn' ? texts.lina1b : texts.lina1c), delay: 25300 },
      { type: "sent", text: texts.mc4, delay: 27000 },
      { type: "received", text: texts.lina7, delay: 28700 },
      { type: "sent", text: texts.mc5, delay: 30400 },
      { type: "received", text: texts.lina8, delay: 32100 },
      { type: "sent", text: texts.mc6, delay: 33800 },
      { type: "received", text: texts.lina9, delay: 35500 },
      { type: "sent", text: texts[tgChoice], delay: 37200, showChoices: true, choiceId: 'tg' },
      { type: "received", text: tgChoice === 'admit_for_you' ? texts.lina2a : (tgChoice === 'admit_change' ? texts.lina2b : texts.lina2c), delay: 38900 },
      { type: "sent", text: texts.msg5, delay: 40600 },
      { type: "received", text: texts.lina10, delay: 42300 },
      { type: "sent", text: texts.mc7, delay: 44000 },
      { type: "received", text: texts.lina11, delay: 45700 },
      { type: "sent", text: texts.msg6, delay: 47400 },
      { type: "received", text: texts.lina12, delay: 49100 },
      { type: "sent", text: texts.mc8, delay: 50800 },
      { type: "received", text: texts.lina13, delay: 52500 },
      { type: "sent", text: texts.msg7, delay: 54200 },
      { type: "received", text: texts.lina14, delay: 55900 },
      { type: "sent", text: texts[dateChoice], delay: 57600, showChoices: true, choiceId: 'date' },
      { type: "received", text: dateChoice === 'agree_obedient' ? texts.lina3a : (dateChoice === 'agree_yours' ? texts.lina3b : texts.lina3c), delay: 59300 },
      { type: "sent", text: texts.mc9, delay: 61000 },
      { type: "received", text: texts.lina15, delay: 62700 },
      { type: "sent", text: texts.msg8, delay: 64400 },
      { type: "received", text: texts.lina16, delay: 66100 },
      { type: "sent", text: texts.mc10, delay: 67800 },
      { type: "received", text: texts.lina17, delay: 69500 },
      { type: "sent", text: texts.msg9, delay: 71200 },
      { type: "received", text: texts.lina18, delay: 72900 },
      { type: "sent", text: texts.mc11, delay: 74600 },
      { type: "received", text: texts.lina19, delay: 76300 },
      { type: "sent", text: texts.msg10, delay: 78000 },
      { type: "received", text: texts.lina20, delay: 79700 },
      { type: "sent", text: texts.mc12, delay: 81400 },
      { type: "received", text: texts.lina21, delay: 83100 },
      { type: "sent", text: texts.msg11, delay: 84800 },
      { type: "received", text: texts.lina22, delay: 86500 },
      { type: "sent", text: texts.mc13, delay: 88200 },
      { type: "received", text: texts.lina23, delay: 89900 },
      { type: "sent", text: texts.msg12, delay: 91600 },
      { type: "received", text: texts.lina24, delay: 93300 },
      { type: "sent", text: texts.mc14, delay: 95000 },
      { type: "received", text: texts.lina25, delay: 96700 },
      { type: "sent", text: texts.msg13, delay: 98400 },
      { type: "received", text: texts.lina26, delay: 100100 },
      { type: "sent", text: texts.mc15, delay: 101800 },
      { type: "received", text: texts.lina27, delay: 103500 },
      { type: "sent", text: texts.msg14, delay: 105200 },
      { type: "received", text: texts.lina28, delay: 106900 },
      { type: "sent", text: texts.mc16, delay: 108600 },
      { type: "received", text: texts.lina29, delay: 110300 },
      { type: "sent", text: texts.msg15, delay: 112000 },
      { type: "received", text: texts.lina30, delay: 113700 },
      { type: "sent", text: texts.mc17, delay: 115400 },
      { type: "received", text: texts.lina31, delay: 117100 },
      { type: "sent", text: texts.mc18, delay: 118800 },
      { type: "received", text: texts.lina32, delay: 120500, nextChapter: "chapter10_submissive" }
    ];
  },
  getChoices(gameState) {
    const lang = gameState.language || 'ru';
    const texts = this.translations[lang];
    return {
      sex: [
        { id: 'apology', text: texts.choice1a },
        { id: 'weak_learn', text: texts.choice1b },
        { id: 'agree_drop', text: texts.choice1c }
      ],
      tg: [
        { id: 'admit_for_you', text: texts.choice2a },
        { id: 'admit_change', text: texts.choice2b },
        { id: 'admit_no_fight', text: texts.choice2c }
      ],
      date: [
        { id: 'agree_obedient', text: texts.choice3a },
        { id: 'agree_yours', text: texts.choice3b },
        { id: 'agree_as_want', text: texts.choice3c }
      ]
    };
  }
};