export default {
  translations: {
    ru: {
      msg1: "Эй, малыш! Снова за компом, рву всех в Доке.",
      mc1: "О, ты опять в игре? А я тут про твои ступни думаю, покажи-ка!",
      lina1: "Серьёзно? Ну, держи, вот мои офигенные ступни на фоне катки. [фото ног на фоне Доки]",
      msg2: "Чёрт, Лина, ты знаешь, как меня завести...",
      lina2: "Ахах, знаю, знаю. Помнишь нашу встречу вчера? Ты был не в форме, а?",
      mc2: "Ну да, признаю, быстро кончил. Но ты вроде не жаловалась?",
      lina3: "Не жаловалась? Ха, твой язык — это просто магия, малыш. Глянь фотку с того вечера, как я довольная. [фото со встречи]",
      msg3: "Вау, ты выглядишь шикарно. Куни правда зашёл?",
      lina4: "О да, это было что-то. А знаешь, у тебя талант. Может, станешь массажистом женских ног? 😏",
      mc3: "Да блин, ты что? Мне твои ступни нравятся, я не хочу чужие!",
      lina5: "Ха, ну да, профессии такой нет — только женские ноги массировать, ахах! Ты бы справился.",
      msg4: "Лина, это не смешно. Я только твои хочу трогать.",
      lina6: "Мои, да? Ну, после вчерашнего это мило звучит. Хотя твои попытки там… немного жалкие были.",
      choice1a: "Жалкие? Ты сама виновата, что меня довела!",
      choice1b: "Это несправедливо, я старался, а не был жалким!",
      choice1c: "Прекрати, я не собираюсь это обсуждать!",
      lina1a: "Виновата? Ха, ты сам виноват, слабак. Учись держать себя.",
      lina1b: "Старался? Ха, зря, если так выглядело. Попробуй лучше.",
      lina1c: "Не обсуждать? Окей, но ты слабак, раз молчишь.",
      mc4: "Жалкие? А ты сама растянута после меня, признай!",
      lina7: "Ого, предъявы? Растянута, говоришь? А ты быстро сдался, не спорь!",
      mc5: "Я не сдавался, ты просто слишком давишь!",
      lina8: "Давлю? Ха, это твоя проблема. Учись держать удар.",
      mc6: "Ладно, но я не слабак, как ты думаешь.",
      lina9: "Забудем? Посмотрим. Но ты реально странный с этими стопами. У тебя же куча ТГ-каналов со ступнями, пиздабол, не отрицай!",
      choice2a: "Это мои дела, не лезь в них!",
      choice2b: "Нет, это не мои каналы, докажу!",
      choice2c: "Давай сменим тему, это не твоё дело!",
      lina2a: "Твои дела? Ха, покажи, что не слабак, тогда!",
      lina2b: "Не твои? Врёшь, докажи, если сможешь!",
      lina2c: "Не моё дело? Окей, но ты подозрительный.",
      msg5: "Лина, оставь это, я не обязан оправдываться.",
      lina10: "Да ладно, шучу. Так что, ещё увидимся?",
      mc7: "Может, если ты перестанешь наезжать.",
      lina11: "Хм, может, завтра вечером? Хотя… Марк предлагал встретиться, он такой интересный.",
      msg6: "Марк? Я не дам тебе с ним встречаться!",
      lina12: "Ой, не кипятись, просто думаю. Он другой, не такой… торопливый, как некоторые.",
      mc8: "Торопливый? Это ты не справилась, а не я!",
      lina13: "Ха, а ты прям в точку бьёшь. Может, и да, может, и нет. Загадки — это моё, малыш.",
      msg7: "Лина, это не смешно, я серьёзно.",
      lina14: "Серьёзно? Ну, давай решим про свидание. Завтра, 7 вечера, мой дом?",
      choice3a: "Ладно, но только если ты без Марка.",
      choice3b: "Предлагаю кафе, а не твой дом.",
      choice3c: "Не хочу завтра, давай позже.",
      lina3a: "Без Марка? Ха, посмотрим, будь в 7!",
      lina3b: "Кафе? Интересно, но я хочу дома. Убеди меня.",
      lina3c: "Позже? Окей, но Марк ждёт.",
      mc9: "Буду, но без твоих игр с Марком.",
      lina15: "Поговорим, если докажешь, что не зря гордишься. А если облажаешься, форс-футджоб!",
      msg8: "Форс-футджоб? Не надейся, я не дам!",
      lina16: "Не дашь? Ха, посмотрим, кто сильнее. Готовься!",
      mc10: "Готовлюсь, но только ради себя.",
      lina17: "Может да, может нет. Увидишь завтра.",
      msg9: "Ты меня бесишь, но я приду.",
      lina18: "Бешу? Это начало. Приходи, узнаешь.",
      mc11: "Приду, но на своих условиях.",
      lina19: "Условия? Ха, планы у меня, ступни ждут!",
      msg10: "Твои ступни — не главное.",
      lina20: "Не главное? Посмотрим, не подведи.",
      mc12: "Принесу, что захочу, а не что ты скажешь.",
      lina21: "Захочешь? Интересно. Масло — если осмелишься!",
      msg11: "Масло? Решу на месте.",
      lina22: "Решай, но не опаздывай!",
      mc13: "Не опоздаю, но ты меня не дави.",
      lina23: "Не давлю? Это веселье. Спокойной!",
      msg12: "Спокойной, но без твоих штучек.",
      lina24: "Разберёмся. Я выигрываю. 😄",
      mc14: "Посмотрим, кто победит.",
      lina25: "Пока, упрямец. Жду!",
      msg13: "Что ты задумала?",
      lina26: "Увидишь, если будешь вовремя. Может, ужин.",
      mc15: "Ужин? Если без Марка.",
      lina27: "Без Марка, если докажешь. Спим.",
      msg14: "Докажу, но ты не командуй.",
      lina28: "Не командую, держу в тонусе. Спи.",
      mc16: "Спи, но я не твой слуга.",
      lina29: "Не слуга? Посмотрим. Спокойной.",
      msg15: "Уверена, что завтра решим?",
      lina30: "Уверена, если не будешь ныть. Отдыхай.",
      mc17: "Отдыхаю, но ты меня злишь.",
      lina31: "Злю? Сам злишься. Спокойной.",
      mc18: "Спокойной, Лина.",
      lina32: "Спокойной, мой упрямый."
    },
    en: {
      msg1: "Hey babe! Back at the PC, crushing it in Dota.",
      mc1: "Oh, gaming again? Been thinking about your feet, show me!",
      lina1: "Seriously? Okay, here are my amazing feet on the game background. [photo of feet on Dota]",
      msg2: "Damn, Lina, you know how to get me going...",
      lina2: "Haha, I know. Remember our meet-up yesterday? You were off your game, huh?",
      mc2: "Yeah, I admit, finished too fast. But you didn’t complain, right?",
      lina3: "Not complain? Haha, your tongue was magic, babe. Check this pic from that night, look how happy I was. [photo from meeting]",
      msg3: "Wow, you look stunning. Cunnilingus really hit the spot?",
      lina4: "Oh yeah, it was something else. You’ve got talent. Maybe become a women’s foot masseur? 😏",
      mc3: "What the hell? No way, I like your feet, I don’t want others!",
      lina5: "Haha, well, there’s no such job—just massaging women’s feet, lol! You’d manage.",
      msg4: "Lina, that’s not funny. I only wanna touch yours.",
      lina6: "Mine, huh? Sounds cute after yesterday. Though your attempts there… kinda pathetic.",
      choice1a: "Pathetic? You’re to blame for driving me crazy!",
      choice1b: "Unfair, I tried, I wasn’t pathetic!",
      choice1c: "Stop it, I won’t discuss this!",
      lina1a: "To blame? Ha, you’re at fault, weakling. Learn control.",
      lina1b: "Tried? Ha, wasted effort if it looked like that. Try better.",
      lina1c: "Not discuss? Okay, but you’re weak for staying quiet.",
      mc4: "Pathetic? You’re stretched out after me, admit it!",
      lina7: "Oh, calling me out? Stretched out, huh? You gave up fast, don’t argue!",
      mc5: "I didn’t give up, you’re just too pushy!",
      lina8: "Pushy? Ha, that’s your problem. Learn to take it.",
      mc6: "Fine, but I’m not weak like you think.",
      lina9: "Forget it? We’ll see. But you’re weird with those feet. You’ve got tons of TG channels with feet, liar, don’t deny it!",
      choice2a: "That’s my business, stay out!",
      choice2b: "No, not my channels, I’ll prove it!",
      choice2c: "Let’s change topic, it’s none of your business!",
      lina2a: "Your business? Ha, prove you’re not weak then!",
      lina2b: "Not yours? Lying, prove it if you can!",
      lina2c: "None of my business? Okay, but you’re suspicious.",
      msg5: "Lina, drop it, I don’t owe you explanations.",
      lina10: "It’s fine, just kidding. So, see you again?",
      mc7: "Maybe, if you stop attacking me.",
      lina11: "Hmm, maybe tomorrow night? Though… Mark suggested meeting up, he’s kinda interesting.",
      msg6: "Mark? I won’t let you meet him!",
      lina12: "Oh, don’t freak out, just thinking. He’s different, not as… rushed as some.",
      mc8: "Rushed? You couldn’t handle it, not me!",
      lina13: "Haha, you hit the nail on the head. Maybe yes, maybe no. Mysteries are mine, babe.",
      msg7: "Lina, this isn’t funny, I’m serious.",
      lina14: "Serious? Fine, let’s settle the date. Tomorrow, 7 PM, my place?",
      choice3a: "Okay, but only if no Mark.",
      choice3b: "Suggest a café, not your place.",
      choice3c: "Not tomorrow, let’s do it later.",
      lina3a: "No Mark? Ha, we’ll see, be there at 7!",
      lina3b: "Café? Interesting, but I want home. Convince me.",
      lina3c: "Later? Okay, but Mark’s waiting.",
      mc9: "I’ll be there, but no games with Mark.",
      lina15: "We will, if you prove you’re not all talk. Flop, and it’s forced footjob!",
      msg8: "Forced footjob? Not happening, I won’t let you!",
      lina16: "Won’t let? Ha, we’ll see who’s stronger. Get ready!",
      mc10: "I’m preparing, but for myself.",
      lina17: "Maybe yes, maybe no. See tomorrow.",
      msg9: "You annoy me, but I’ll come.",
      lina18: "Annoy? That’s the start. Come, find out.",
      mc11: "I’ll come, but on my terms.",
      lina19: "Terms? Ha, I’ve got plans, feet are waiting!",
      msg10: "Your feet aren’t everything.",
      lina20: "Not everything? We’ll see, don’t fail.",
      mc12: "I’ll bring what I want, not what you say.",
      lina21: "Want? Interesting. Oil if you dare!",
      msg11: "Oil? I’ll decide there.",
      lina22: "Decide, but don’t be late!",
      mc13: "Won’t be late, but don’t push me.",
      lina23: "Not pushing? That’s fun. Night!",
      msg12: "Night, but no tricks.",
      lina24: "We’ll sort it. I win. 😄",
      mc14: "We’ll see who wins.",
      lina25: "Bye, stubborn. Waiting!",
      msg13: "What are you planning?",
      lina26: "You’ll see if on time. Maybe dinner.",
      mc15: "Dinner? Only if no Mark.",
      lina27: "No Mark if you prove it. Sleep.",
      msg14: "I’ll prove it, but no orders.",
      lina28: "Not ordering, keeping you sharp. Sleep.",
      mc16: "Sleep, but I’m no servant.",
      lina29: "Not servant? We’ll see. Night.",
      msg15: "Sure we’ll settle tomorrow?",
      lina30: "Sure, if no whining. Rest.",
      mc17: "Resting, but you piss me off.",
      lina31: "Piss off? You do it to yourself. Night.",
      mc18: "Night, Lina.",
      lina32: "Night, my stubborn."
    }
  },
  getText(gameState) {
    const lang = gameState.language || 'ru';
    const texts = this.translations[lang];
    const sexChoice = gameState.choices['chapter9_sex'] || 'blame_her';
    const tgChoice = gameState.choices['chapter9_tg'] || 'my_business';
    const dateChoice = gameState.choices['chapter9_date'] || 'no_mark';
    return [
      { type: "received", text: texts.msg1, delay: 1500 },
      { type: "sent", text: texts.mc1, delay: 3200 },
      { type: "received", text: texts.lina1, image: "lina_feet_dota.jpg", delay: 4900 },
      { type: "sent", text: texts.msg2, delay: 6600 },
      { type: "received", text: texts.lina2, delay: 8300 },
      { type: "sent", text: texts.mc2, delay: 10000 },
      { type: "received", text: texts.lina3, image: "lina_meeting.jpg", delay: 11700 },
      { type: "sent", text: texts.msg3, delay: 13400 },
      { type: "received", text: texts.lina4, delay: 15100 },
      { type: "sent", text: texts.mc3, delay: 16800 },
      { type: "received", text: texts.lina5, delay: 18500 },
      { type: "sent", text: texts.msg4, delay: 20200 },
      { type: "received", text: texts.lina6, delay: 21900 },
      { type: "sent", text: texts[sexChoice], delay: 23600, showChoices: true, choiceId: 'sex' },
      { type: "received", text: sexChoice === 'blame_her' ? texts.lina1a : (sexChoice === 'tried_unfair' ? texts.lina1b : texts.lina1c), delay: 25300 },
      { type: "sent", text: texts.mc4, delay: 27000 },
      { type: "received", text: texts.lina7, delay: 28700 },
      { type: "sent", text: texts.mc5, delay: 30400 },
      { type: "received", text: texts.lina8, delay: 32100 },
      { type: "sent", text: texts.mc6, delay: 33800 },
      { type: "received", text: texts.lina9, delay: 35500 },
      { type: "sent", text: texts[tgChoice], delay: 37200, showChoices: true, choiceId: 'tg' },
      { type: "received", text: tgChoice === 'my_business' ? texts.lina2a : (tgChoice === 'prove_not_mine' ? texts.lina2b : texts.lina2c), delay: 38900 },
      { type: "sent", text: texts.msg5, delay: 40600 },
      { type: "received", text: texts.lina10, delay: 42300 },
      { type: "sent", text: texts.mc7, delay: 44000 },
      { type: "received", text: texts.lina11, delay: 45700 },
      { type: "sent", text: texts.msg6, delay: 47400 },
      { type: "received", text: texts.lina12, delay: 49100 },
      { type: "sent", text: texts.mc8, delay: 50800 },
      { type: "received", text: texts.lina13, delay: 52500 },
      { type: "sent", text: texts.msg7, delay: 54200 },
      { type: "received", text: texts.lina14, delay: 55900 },
      { type: "sent", text: texts[dateChoice], delay: 57600, showChoices: true, choiceId: 'date' },
      { type: "received", text: dateChoice === 'no_mark' ? texts.lina3a : (dateChoice === 'cafe_suggest' ? texts.lina3b : texts.lina3c), delay: 59300 },
      { type: "sent", text: texts.mc9, delay: 61000 },
      { type: "received", text: texts.lina15, delay: 62700 },
      { type: "sent", text: texts.msg8, delay: 64400 },
      { type: "received", text: texts.lina16, delay: 66100 },
      { type: "sent", text: texts.mc10, delay: 67800 },
      { type: "received", text: texts.lina17, delay: 69500 },
      { type: "sent", text: texts.msg9, delay: 71200 },
      { type: "received", text: texts.lina18, delay: 72900 },
      { type: "sent", text: texts.mc11, delay: 74600 },
      { type: "received", text: texts.lina19, delay: 76300 },
      { type: "sent", text: texts.msg10, delay: 78000 },
      { type: "received", text: texts.lina20, delay: 79700 },
      { type: "sent", text: texts.mc12, delay: 81400 },
      { type: "received", text: texts.lina21, delay: 83100 },
      { type: "sent", text: texts.msg11, delay: 84800 },
      { type: "received", text: texts.lina22, delay: 86500 },
      { type: "sent", text: texts.mc13, delay: 88200 },
      { type: "received", text: texts.lina23, delay: 89900 },
      { type: "sent", text: texts.msg12, delay: 91600 },
      { type: "received", text: texts.lina24, delay: 93300 },
      { type: "sent", text: texts.mc14, delay: 95000 },
      { type: "received", text: texts.lina25, delay: 96700 },
      { type: "sent", text: texts.msg13, delay: 98400 },
      { type: "received", text: texts.lina26, delay: 100100 },
      { type: "sent", text: texts.mc15, delay: 101800 },
      { type: "received", text: texts.lina27, delay: 103500 },
      { type: "sent", text: texts.msg14, delay: 105200 },
      { type: "received", text: texts.lina28, delay: 106900 },
      { type: "sent", text: texts.mc16, delay: 108600 },
      { type: "received", text: texts.lina29, delay: 110300 },
      { type: "sent", text: texts.msg15, delay: 112000 },
      { type: "received", text: texts.lina30, delay: 113700 },
      { type: "sent", text: texts.mc17, delay: 115400 },
      { type: "received", text: texts.lina31, delay: 117100 },
      { type: "sent", text: texts.mc18, delay: 118800 },
      { type: "received", text: texts.lina32, delay: 120500, nextChapter: "chapter10_resist" }
    ];
  },
  getChoices(gameState) {
    const lang = gameState.language || 'ru';
    const texts = this.translations[lang];
    return {
      sex: [
        { id: 'blame_her', text: texts.choice1a },
        { id: 'tried_unfair', text: texts.choice1b },
        { id: 'stop_discuss', text: texts.choice1c }
      ],
      tg: [
        { id: 'my_business', text: texts.choice2a },
        { id: 'prove_not_mine', text: texts.choice2b },
        { id: 'change_topic', text: texts.choice2c }
      ],
      date: [
        { id: 'no_mark', text: texts.choice3a },
        { id: 'cafe_suggest', text: texts.choice3b },
        { id: 'later_refuse', text: texts.choice3c }
      ]
    };
  }
};