export default {
  getText(gameState) {
    const isSubmissive = gameState.choices['chapter6'] === 'submissive';
    const texts = gameState.language === 'en' ? {
      msg3_sent: "But you're posing so close to him, almost like you're together. Doesn't that bother you?",
      msg4_received: "Bother me? Why would it? It's just work. And besides, I think they turned out great. Want to see?",
      msg5_received: "Look, I know it looks a bit intimate, but it's just a photoshoot. We had to get into character.",
      msg5_received_image1: "img/lina_photoshoot_1.jpg",
      msg6_sent: "Wow, that's... intense. You look amazing, but seeing you with him like that...",
      msg7_received: "Like what? We're just models doing our job. Don't tell me you're getting jealous over a photo.",
      msg8_sent: "I'm not jealous, it's just... I don't know, it feels strange.",
      msg9_received: "Strange good or strange bad? Because from where I'm standing, it looks like you're into it.",
      msg10_sent: "What? No, I mean, yes, you look hot, but...",
      msg11_received: "But what? Spit it out.",
      msg12_sent: "It's just that, seeing you with another guy like that, it makes me feel... I don't know, a mix of things.",
      msg13_received: "A mix of things, huh? Like what? Excited? Turned on?",
      msg14_sent: "Maybe a little, but also worried, you know?",
      msg15_received: "Worried about what? That I might leave you for Alex or something?",
      msg16_sent: "Well, yeah, something like that.",
      msg17_received: "Oh, please. Alex is just a colleague. You're my boyfriend, remember?",
      msg18_sent: "I know, but seeing those photos, it's hard not to think about it.",
      msg19_received: "Think about what? Me being with someone else?",
      msg20_sent: "Yeah, I guess.",
      msg21_received: "Well, maybe you should think about it more. It might be good for you.",
      msg22_sent: "What do you mean?",
      msg23_received: "I mean, sometimes a little fantasy can spice things up, you know?",
      msg24_sent: "I'm not sure about that.",
      msg25_received: "Come on, don't be such a prude. Let's see if there are more photos.",
      msg26_image: "img/lina_photoshoot_2.jpg",
      msg26_received: "Look, he's hugging me from behind. That's even more intimate.",
      msg27_sent: "Oh my god, he's hugging you from behind. That's even more intimate.",
      msg28_received: "Yeah, and? It's just a pose. But I can see why you'd think that.",
      msg29_sent: "It's just that, you never pose like that with me.",
      msg30_received: "Well, maybe I should. Do you want me to?",
      msg31_sent: "I don't know, maybe. But seriously, why don't you send me photos like that?",
      msg32_received: "Because you never asked. Do you want me to send you some?",
      msg33_sent: "You don't even send me stuff like that, what the hell?",
      msg34_received: "Damn, you're right. Gotta fix that.",
      msg35_received_showChoices: "So what do you want me to send you?",
      
      }:{
      msg3_sent: "Но ты так близко к нему, почти как пара. Разве это тебя не беспокоит?",
      msg4_received: "Беспокоит? Почему? Это просто работа. И к тому же, я думаю, они получились отлично. Хочешь посмотреть?",
      msg5_received: "Смотри, я знаю, что это выглядит немного интимно, но это просто фотосессия. Мы должны были войти в образ.",
      msg5_received_image1: "img/lina_photoshoot_1.jpg",
      msg6_sent: "Вау, это... интенсивно. Ты выглядишь потрясающе, но видеть тебя с ним так...",
      msg7_received: "Так как? Мы просто модели, делаем свою работу. Не говори мне, что ты ревнуешь из-за фотографии.",
      msg8_sent: "Я не ревную, просто... не знаю, это странно чувствую.",
      msg9_received: "Странно хорошо или странно плохо? Потому что с моей точки зрения, кажется, тебе это нравится.",
      msg10_sent: "Что? Нет, я имею в виду, да, ты выглядишь горячо, но...",
      msg11_received: "Но что? Выпаливай.",
      msg12_sent: "Просто, видеть тебя с другим парнем так, это заставляет меня чувствовать... не знаю, смесь чувств.",
      msg13_received: "Смесь чувств, а? Каких именно? Взволнованный? Взбудораженный?",
      msg14_sent: "Может быть, чуть-чуть, но также и обеспокоенный, знаешь?",
      msg15_received: "Обеспокоенный чем? Что я могу уйти к Алексу или что-то в этом роде?",
      msg16_sent: "Ну, да, что-то вроде того.",
      msg17_received: "О, пожалуйста. Алекс просто коллега. Ты мой парень, помнишь?",
      msg18_sent: "Я знаю, но видя эти фото, трудно не думать об этом.",
      msg19_received: "Думать о чем? О том, что я с кем-то другим?",
      msg20_sent: "Да, наверное.",
      msg21_received: "Ну, может быть, тебе стоит подумать об этом больше. Это может пойти тебе на пользу.",
      msg22_sent: "Что ты имеешь в виду?",
      msg23_received: "Я имею в виду, иногда немного фантазий может добавить остроты, знаешь?",
      msg24_sent: "Я не уверен насчет этого.",
      msg25_received: "Да ладно, не будь таким занудой. Давай посмотрим, есть ли еще фото.",
      msg26_image: "img/lina_photoshoot_2.jpg",
      msg26_received: "Смотри, он обнимает меня сзади. Это еще более интимно.",
      msg27_sent: "О боже, он обнимает тебя сзади. Это еще более интимно.",
      msg28_received: "Да, и что? Это просто поза. Но я понимаю, почему ты так думаешь.",
      msg29_sent: "Просто, ты никогда не позируешь так со мной.",
      msg30_received: "Ну, может быть, мне стоит. Хочешь, чтобы я позировала так для тебя?",
      msg31_sent: "Не знаю, может быть. Но серьезно, почему ты не шлешь мне такие фото?",
      msg32_received: "Потому что ты никогда не просил. Хочешь, чтобы я шлепнула тебе несколько?",
      msg33_sent: "Ты даже мне такое не шлешь, что за фигня?",
      msg34_received: "Блин, ты прав. Надо исправить это.",
      msg35_received_showChoices: "Так что ты хочешь, чтобы я тебе отправила?",
      };
    return [
      { type: "sent", text: texts.msg3_sent, delay: 1000 },
      { type: "received", text: texts.msg4_received, delay: 2700 },
      { type: "photo", text: texts.msg5_received, src: texts.msg5_received_image1, delay: 4400 },
      { type: "sent", text: texts.msg6_sent, delay: 6100 },
      { type: "received", text: texts.msg7_received, delay: 7800 },
      { type: "sent", text: texts.msg8_sent, delay: 9500 },
      { type: "received", text: texts.msg9_received, delay: 11200 },
      { type: "sent", text: texts.msg10_sent, delay: 12900 },
      { type: "received", text: texts.msg11_received, delay: 14600 },
      { type: "sent", text: texts.msg12_sent, delay: 16300 },
      { type: "received", text: texts.msg13_received, delay: 18000 },
      { type: "sent", text: texts.msg14_sent, delay: 19700 },
      { type: "received", text: texts.msg15_received, delay: 21400 },
      { type: "sent", text: texts.msg16_sent, delay: 23100 },
      { type: "received", text: texts.msg17_received, delay: 24800 },
      { type: "sent", text: texts.msg18_sent, delay: 26500 },
      { type: "received", text: texts.msg19_received, delay: 28200 },
      { type: "sent", text: texts.msg20_sent, delay: 29900 },
      { type: "received", text: texts.msg21_received, delay: 31600 },
      { type: "sent", text: texts.msg22_sent, delay: 33300 },
      { type: "received", text: texts.msg23_received, delay: 36500 },
      { type: "sent", text: texts.msg24_sent, delay: 38200 },
      { type: "received", text: texts.msg25_received, delay: 39900 },
      { type: "photo", text: texts.msg26_received, src: texts.msg26_image, delay: 41600 },
      { type: "sent", text: texts.msg27_sent, delay: 43300 },
      { type: "received", text: texts.msg28_received, delay: 45000 },
      { type: "sent", text: texts.msg29_sent, delay: 46700 },
      { type: "received", text: texts.msg30_received, delay: 48400 },
      { type: "sent", text: texts.msg31_sent, delay: 50100 },
      { type: "received", text: texts.msg32_received, delay: 53500 },
      { type: "sent", text: texts.msg33_sent, delay: 55200 },
      { type: "received", text: texts.msg34_received, delay: 56900 },
      { type: "received", text: texts.msg35_received_showChoices, delay: 58600, showChoices: true }
    ];
  },
  getChoices(gameState) {
    const texts = gameState.language === 'en' ? {
      choice1: "Yes, send me some intimate photos",
      choice2: "Actually, I'd prefer something else, like your feet pictures",
      result1_image: "img/lina_intimate_photo.jpg",
      result2_image: "img/lina_soles_photo.jpg",
      lina_answer: "Enjoy... ;)",
      }:{
      choice1: "Да, пришли мне интимные фото",      
      choice2: "На самом деле, я бы предпочел что-то другое, например, фото твоих ступней",
      result1_image: "img/lina_intimate_photo.jpg",
      result2_image: "img/lina_soles_photo.jpg",
      lina_answer: "Наслаждайся... ;)",
    };
    return [
      {
        id: "ask_intimate",
        text: texts.choice1,
        result: [
          { type: "photo", text: texts.lina_answer, src: texts.result1_image, delay: 2000, nextChapter: "chapter8_intimate" }
        ]
      },
      {
        id: "ask_feet",
        text: texts.choice2,
        result: [
          { type: "photo", text: texts.lina_answer, src: texts.result2_image, delay: 2000, nextChapter: "chapter8_feet" }
        ]
      }
    ];
  }
};